// date
// inclusion_q1
// inclusion_q2
// inclusion_q3
// exclusion_q1
// exclusion_q2
// exclusion_q3
// exclusion_q4
// exclusion_q5
// birth_date
// gender

mh__diabetes

BMI
ans__anthropometry__calf_circumference
ans__anthropometry__current_bmi
ans__anthropometry__current_weight
ans__anthropometry__difference_percentage
ans__anthropometry__initial_weight
au__preperitoneal
au__superficial
au__total_adipose_tissue
bi__asmm
bi__bcm
bi__bcm_h
bi__body_fat
bi__ecw
bi__ffm
bi__fm
bi__hydratation
bi__icw
bi__phase_angle
bi__reactance
bi__resistance
bi__smi
bi__standarized_phase_angle
bi__tbm
calf_circumference
cppi__considers_that_patient_perceives_improvement
cppi__considers_that_patient_perceives_improvement_reasons
created_at
current_body_weight

dexa__ffm
dexa__fm
does_the_patient_have_sarcopenia
dynamometry
dynamometry__not_possible

height
hfnr__followed_prescribed_nutritional_recommendation
hfnr__not_followed_prescribed_recommendation
hfnr__percentage_of_adherece_to_recommendations
hfppar__not_followed_prescribed_recommendation
hfppar_followed_prescribed_physical_activity_recommendation
hfppar_percentage_of_adherece_to_recommendations
hospitalization
hospitalization_reason
id

loss_last_six_months
mar__normal
mh__cancer

mh__epoc
mh__heart_failure
mh__inflammatory_bowel_disease
mh__liver_diseases
mh__neurological_disease
mh__other_chronic_diseases
mh__others
mh__others_description
mh__renal_failure
ms__other
ms__other_description
ms__result
ms__sarc_f
mu__adipose_tissue
mu__area
mu__axes_xax
mu__axes_yax
mu__circumference
nd__glim
nd__mna
nd__other
nd__other_description
nd__vgs
ns__conut
ns__mis
ns__mna_sf
ns__must
ns__nrs_2002
ns__other
ns__other_description
ns__result
ns__snaq
nt__has_not_got_improvement_reason
nt__improvement
nt__objective_reached
nt__objective_reached_reason
nt__planted_objectives__muscle_gain
nt__planted_objectives__other
nt__planted_objectives__other_description
nt__planted_objectives__preservation_status
nt__planted_objectives__weight_gain
nt__pnr
nt__pnr_percent
nt__reason
nt__start
nti__dietary_modifications
nti__en
nti__en__option
nti__en__other_description
nti__parental_nutrition
nti__son
nti__son__option
nti__son__other_description
pa__aerobic_predominance
pa__hpftppar
pa__hpftppar_percent
pa__mixed
pa__predominance_muscular_strength
pa__prescribed
pa__prescribed_reasons
pa__reason
patient_current_situation
patient_current_situation_date
patient_id
patient_malnourished
patient_malnourished__diagnosis
patient_malnourished__procedure
refers_patient_to_begin_nutritional_treatment
rng__has_reached_nutritional_goal
rng__has_reached_nutritional_goal_reasons
sarcopenia__diagnosis
scheduled_visit
tc__ffm
tc__fm
test_chair__not_possible
test_chair_five_repetitions
updated_at
usual_body_weight
valuation_date
visit_type
weight_loss_percentage
