'use client'
import { useCrdStore } from '@/store'

export const useInitializeForm = () => {
	const { setInitial, setVisit1 } = useCrdStore()

	const initializeForm = (visit: any) => {
		setInitial({
			date: visit.date,
			inclusion_q1: visit.inclusion_q1,
			inclusion_q2: visit.inclusion_q2,
			inclusion_q3: visit.inclusion_q3,
			exclusion_q1: visit.exclusion_q1,
			exclusion_q2: visit.exclusion_q2,
			exclusion_q3: visit.exclusion_q3,
			exclusion_q4: visit.exclusion_q4,
			exclusion_q5: visit.exclusion_q5,
			birth_date: visit.birth_date,
			gender: visit.gender,
			mh__diabetes: visit.mh__diabetes,
			mh__epoc: visit.mh__epoc,
			mh__heart_failure: visit.mh__heart_failure,
			mh__cancer: visit.mh__cancer,
			mh__neurological_disease: visit.mh__neurological_disease,
			mh__liver_diseases: visit.mh__liver_diseases,
			mh__inflammatory_bowel_disease: visit.mh__inflammatory_bowel_disease,
			mh__renal_failure: visit.mh__renal_failure,
			mh__other_chronic_diseases: visit.mh__other_chronic_diseases,
			mh__others: visit.mh__others,
			mh__others_description: visit.mh__others_description,
			valuation_date: visit.valuation_date,
			hospitalization: visit.hospitalization,
			scheduled_visit: visit.scheduled_visit,
			current_body_weight: visit.current_body_weight,
			usual_body_weight: visit.usual_body_weight,
			loss_last_six_months: visit.loss_last_six_months,
			weight_loss_percentage: visit.weight_loss_percentage,
			height: visit.height,
			BMI: visit.BMI,
			calf_circumference: visit.calf_circumference,
			ns__must: visit.ns__must,
			ns__nrs_2002: visit.ns__nrs_2002,
			ns__mna_sf: visit.ns__mna_sf,
			ns__mis: visit.ns__mis,
			ns__snaq: visit.ns__snaq,
			ns__conut: visit.ns__conut,
			ns__other: visit.ns__other,
			ns__other_description: visit.ns__other_description,
			ns__result: visit.ns__result,
			ms__sarc_f: visit.ms__sarc_f,
			ms__other: visit.ms__other,
			ms__other_description: visit.ms__other_description,
			ms__result: visit.ms__result,
			nd__glim: visit.nd__glim,
			nd__mna: visit.nd__mna,
			nd__vgs: visit.nd__vgs,
			nd__other: visit.nd__other,
			patient_malnourished: visit.patient_malnourished,
			patient_malnourished__diagnosis: visit.patient_malnourished__diagnosis,
			patient_malnourished__procedure: visit.patient_malnourished__procedure,
			does_the_patient_have_sarcopenia: visit.does_the_patient_have_sarcopenia,
			sarcopenia__diagnosis: visit.sarcopenia__diagnosis,
			dynamometry: visit.dynamometry,
			dynamometry__not_possible: visit.dynamometry__not_possible,
			test_chair_five_repetitions: visit.test_chair_five_repetitions,
			test_chair__not_possible: visit.test_chair__not_possible,
			bi__hydratation: visit.bi__hydratation,

			bi__tbm: visit.bi__tbm,
			bi__ecw: visit.bi__ecw,
			bi__icw: visit.bi__icw,
			bi__ffm: visit.bi__ffm,
			bi__fm: visit.bi__fm,
			bi__bcm: visit.bi__bcm,
			bi__bcm_h: visit.bi__bcm_h,
			bi__asmm: visit.bi__asmm,
			bi__smi: visit.bi__smi,
			bi__body_fat: visit.bi__body_fat,
			dexa__ffm: visit.dexa__ffm,
			dexa__fm: visit.dexa__fm,
			tc__ffm: visit.tc__ffm,
			tc__fm: visit.tc__fm,
			au__total_adipose_tissue: visit.au__total_adipose_tissue,
			au__superficial: visit.au__superficial,
			au__preperitoneal: visit.au__preperitoneal,
			mu__area: visit.mu__area,
			mu__circumference: visit.mu__circumference,
			mu__axes_xax: visit.mu__axes_xax,
			mu__axes_yax: visit.mu__axes_yax,
			mu__adipose_tissue: visit.mu__adipose_tissue,
			mar__normal: visit.mar__normal,
			nt__planted_objectives__weight_gain:
				visit.nt__planted_objectives__weight_gain,
			nt__planted_objectives__muscle_gain:
				visit.nt__planted_objectives__muscle_gain,
			nt__planted_objectives__preservation_status:
				visit.nt__planted_objectives__preservation_status,
			nt__planted_objectives__other: visit.nt__planted_objectives__other,
			nt__planted_objectives__other_description:
				visit.nt__planted_objectives__other_description,
			nt__start: visit.nt__start,
			nti__parental_nutrition: visit.nti__parental_nutrition,
			nti__dietary_modifications: visit.nti__dietary_modifications,
			nti__son: visit.nti__son,
			nti__son__option: visit.nti__son__option ?? [],
			nti__son__other_description: visit.nti__son__other_description,
			nti__en: visit.nti__en,
			nti__en__option: visit.nti__en__option ?? [],
			nti__en__other_description: visit.nti__en__other_description,
			refers_patient_to_begin_nutritional_treatment: visit.refers_patient_to_begin_nutritional_treatment,
			pa__prescribed: visit.pa__prescribed,
			pa__aerobic_predominance: visit.pa__aerobic_predominance,
			pa__predominance_muscular_strength: visit.pa__predominance_muscular_strength,
			pa__mixed: visit.pa__mixed,
		})

		setVisit1({
			patient_current_situation: visit.patient_current_situation,
			patient_current_situation_date: visit.patient_current_situation_date,
			ns__result: visit.ns__result,
			ms__result: visit.ms__result,
			ans__anthropometry__current_weight:
				visit.ans__anthropometry__current_weight,
			ans__anthropometry__initial_weight:
				visit.ans__anthropometry__initial_weight,
			ans__anthropometry__difference_percentage:
				visit.ans__anthropometry__difference_percentage,
			ans__anthropometry__current_bmi: visit.ans__anthropometry__current_bmi,
			ans__anthropometry__calf_circumference:
				visit.ans__anthropometry__calf_circumference,
			dynamometry: visit.dynamometry,
			dynamometry__not_possible: visit.dynamometry__not_possible,
			test_chair_five_repetitions: visit.test_chair_five_repetitions,
			test_chair__not_possible: visit.test_chair__not_possible,
			bi__hydratation: visit.bi__hydratation,
			bi__tbm: visit.bi__tbm,
			bi__ecw: visit.bi__ecw,
			bi__icw: visit.bi__icw,
			bi__ffm: visit.bi__ffm,
			bi__fm: visit.bi__fm,
			bi__bcm: visit.bi__bcm,
			bi__bcm_h: visit.bi__bcm_h,
			bi__asmm: visit.bi__asmm,
			bi__smi: visit.bi__smi,
			bi__body_fat: visit.bi__body_fat,
			bi__resistance: visit.bi__resistance,
			bi__reactance: visit.bi__reactance,
			bi__phase_angle: visit.bi__phase_angle,
			bi__standarized_phase_angle: visit.bi__standarized_phase_angle,
			dexa__ffm: visit.dexa__ffm,
			dexa__fm: visit.dexa__fm,
			tc__ffm: visit.tc__ffm,
			tc__fm: visit.tc__fm,
			au__total_adipose_tissue: visit.au__total_adipose_tissue,
			au__superficial: visit.au__superficial,
			au__preperitoneal: visit.au__preperitoneal,
			mu__area: visit.mu__area,
			mu__circumference: visit.mu__circumference,
			mu__axes_xax: visit.mu__axes_xax,
			mu__axes_yax: visit.mu__axes_yax,
			mu__adipose_tissue: visit.mu__adipose_tissue,
			mar__normal: visit.mar__normal,
			hfnr__followed_prescribed_nutritional_recommendation:
				visit.hfnr__followed_prescribed_nutritional_recommendation,
			hfnr__percentage_of_adherece_to_recommendations:
				visit.hfnr__percentage_of_adherece_to_recommendations,
			hfnr__not_followed_prescribed_recommendation:
				visit.hfnr__not_followed_prescribed_recommendation,
			rng__has_reached_nutritional_goal:
				visit.rng__has_reached_nutritional_goal,
			rng__has_reached_nutritional_goal_reasons:
				visit.rng__has_reached_nutritional_goal_reasons,
			cppi__considers_that_patient_perceives_improvement:
				visit.cppi__considers_that_patient_perceives_improvement,
			cppi__considers_that_patient_perceives_improvement_reasons:
				visit.cppi__considers_that_patient_perceives_improvement_reasons,
			hfppar_followed_prescribed_physical_activity_recommendation:
				visit.hfppar_followed_prescribed_physical_activity_recommendation,
			hfppar_percentage_of_adherece_to_recommendations:
				visit.hfppar_percentage_of_adherece_to_recommendations,
			hfppar__not_followed_prescribed_recommendation:
				visit.hfppar__not_followed_prescribed_recommendation,
		})
	}

	return { initializeForm }
}
